# Generated by Django 3.1.7 on 2021-03-14 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
