# Generated by Django 3.1.7 on 2021-03-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210314_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
