# Generated by Django 3.1.7 on 2021-03-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210315_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='unsnippet', max_length=100),
        ),
    ]
