# Generated by Django 3.1.7 on 2021-03-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210315_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='jsnvs', max_length=100),
            preserve_default=False,
        ),
    ]
